<?php

return [
    [
        'key'   => 'sales.payment_methods.wompi',
        'name'  => 'Wompi',
        'sort'  => 1,
        'info'  => 'Widget wompi',
        'fields' => [
            [
                'name'          => 'title',
                'title'         => 'Título',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
                'info'          => 'Nombre que verá el cliente en el checkout',
            ],
            [
                'name'          => 'description',
                'title'         => 'Descripción',
                'type'          => 'textarea',
                'channel_based' => true,
                'locale_based'  => true,
                'info'          => 'Texto que aparece debajo del método de pago',
            ],
            [
                'name'          => 'image',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.logo',
                'type'          => 'image',
                'info'          => 'admin::app.configuration.index.sales.payment-methods.logo-information',
                'channel_based' => false,
                'locale_based'  => false,
                'validation'    => 'mimes:bmp,jpeg,jpg,png,webp',
            ],
            [
                'name'          => 'active',
                'title'         => 'Habilitar',
                'type'          => 'boolean',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => false,
                'info'          => 'Activa o desactiva Wompi',
            ],
            [
                'name'          => 'public_key',
                'title'         => 'Public Key',
                'type'          => 'text',
                'channel_based' => false,
                'locale_based'  => false,
                'info'          => 'Llave pública de tu cuenta Wompi',
            ],
            [
                'name'          => 'private_key',
                'title'         => 'Private Key',
                'type'          => 'password',
                'channel_based' => false,
                'locale_based'  => false,
                'info'          => 'Llave privada de tu cuenta Wompi',
            ],
            [
                'name'          => 'integrity_key',
                'title'         => 'Integrity Key',
                'type'          => 'password',
                'channel_based' => false,
                'locale_based'  => false,
                'info'          => 'Llave de integridad proporcionada por Wompi para firmar las transacciones',
            ],
            [
                'name'          => 'sandbox',
                'title'         => 'Modo Sandbox',
                'type'          => 'boolean',
                'channel_based' => false,
                'locale_based'  => false,
                'info'          => 'Activa el modo prueba de Wompi (sandbox)',
            ],
            [
                'name'          => 'event_key',
                'title'         => 'Event Key',
                'type'          => 'text',
                'channel_based' => false,
                'locale_based'  => false,
                'info'          => 'Nombre del evento para capturar callbacks del widget (data-event)',
            ],
        ],
    ],
];
